In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)
a

(2, 7)


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [3]:
# Get a specific element [r, c]
print(a[1][5])
print(a[1,5])
print(a[1,-2])

13
13
13


In [4]:
# Get a specific row 
print(a[0])
print(a[0,:])
print(a[0][:])
a[0,:]
# Same with columns

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# Fancy Way [startindex:endindex:stepsize] (Exclusive)
print(a[0, 1:6:2])
print(a[0, 1:-2:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4]
[2 4 6]


In [6]:
# Change element 
print(a)
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [11]:
# 3D Example 
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element ((work outside in)
print(b[0,1,1])
print(b[:,1,:])

4
[[3 4]
 [7 8]]


In [18]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
