In [7]:
import numpy as np

In [28]:
# BASICS
a = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [13]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
print(b)
b


[[9. 8. 7.]
 [1. 2. 3.]]


array([[9., 8., 7.],
       [1., 2., 3.]])

In [29]:
# Get dimension - Gives number of dimensions 
print(a.ndim)
print(b.ndim)

1
2


In [30]:
# Get shape - Gives exact dimentions 
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [38]:
# Get type
print(a.dtype)

#Specify data type which we can to use
c = np.array([1,2,3,4], dtype='int16')
print(c.dtype)

int64
int16


In [44]:
# Get Size - Size in bytes 
print(a.itemsize)
print(c.itemsize)
print(b.itemsize)

8
2
8


In [46]:
# Get total size - Total size of array in bytes 
print(a.size*a.itemsize)
print(c.size*c.itemsize)
print(b.size*b.itemsize)

# Or directly use 
print(a.nbytes)
print(c.nbytes)
print(b.nbytes)

24
8
48
24
8
48
