In [2]:
import numpy as np

In [8]:
# All 0s matrix
print(np.zeros(5))
print(np.zeros((2,2)))
print(np.zeros((2,3,3)))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [16]:
# All 1s matrix
print(np.ones((3,2,2)))
print(np.ones(((3,2,2)), dtype='int16'))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [21]:
# Any other number 
print(np.full((2,2),99,))
print(np.full((2,2),99, dtype='float32'))

[[99 99]
 [99 99]]
[[99. 99.]
 [99. 99.]]


In [27]:
# Any other number (full-like)
a = np.array(([1,2,3,4],[5,6,7,8]))
print(a)
print(np.full_like(a,4))
print(np.full(a.shape,4))

[[1 2 3 4]
 [5 6 7 8]]
[[4 4 4 4]
 [4 4 4 4]]
[[4 4 4 4]
 [4 4 4 4]]


In [32]:
# Random decimal number 
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.24262934 0.50901562]
 [0.26551808 0.19845125]
 [0.88983397 0.43358791]
 [0.45817678 0.5802989 ]]
[[0.24895646 0.80911616 0.29945262 0.63239496]
 [0.25562771 0.43871603 0.10473332 0.25375283]]


In [41]:
# Random integer values 
print(np.random.randint(7))
print(np.random.randint(7,size=(3,3)))
print(np.random.randint(4,7,size=(3,3))) 
# 7 is excluded

2
[[4 0 3]
 [3 2 1]
 [6 3 5]]
[[5 4 6]
 [4 4 4]
 [4 5 6]]


# Identity matrix
print(np.identity(3))
print(np.identity(5,dtype='int16'))

In [57]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

arr1 = np.array([[1,2,3]])
r2=np.repeat(arr1,3)
r3=np.repeat(arr1,3,axis=0)
print(r2)
print(r3)

[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [71]:
# Prac
b = np.ones((5,5),dtype='int16')
print(b)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
b[1:-1,1:-1]=z
# b[1:4,1:4]=z
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [74]:
# Be careful when copying arrays 
a = np.array([1,2,3])
b = a
print(a)
print(b)

b[0] = 100
print(b)
print(a)

# Same like in java b is not a copy of a rather it is pointing to a

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


In [75]:
# Instead use .copy() function
a = np.array([1,2,3])
b = a.copy()
print(a)
print(b)

b[0] = 100
print(b)
print(a)


[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]
