In [2]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a/2)
a-=2
print(a)

[1 2 3 4]
[3 4 5 6]
[0.5 1.  1.5 2. ]
[-1  0  1  2]


In [17]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
print(a+b)
print(a**2)

[2 2 4 4]
[ 1  4  9 16]


In [21]:
# Take the sin of all values 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [31]:
 # Linear Algebra 

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [33]:
# Determinant of a matrix 
c = np.identity(3)
print(np.linalg.det(c)) 

1.0


In [ ]:
# Also has functions for eigen values, inverse, transpose, trace, matrix norm etc.
# https://numpy.org/doc/stable/reference/routines.linalg.html