In [1]:
import numpy as np

In [11]:
# Reshape Array

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((8,1))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


In [14]:
# Vertically Stacking arrays 

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


# Horizontal Stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

print(np.hstack((h1,h2)))


#### Miscellaneous

In [29]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter = ',')
print(filedata)

print(filedata.astype('int32'))
print(filedata)

filedata = filedata.astype('int32')

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


 #### Boolean Masking and Advanced Indexing 

In [34]:
print(filedata > 50)
print(filedata[filedata > 50])

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]


In [38]:
# You can index with a list in Numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] 

array([2, 3, 9])

In [45]:
# If any of the values from any column/row is greater than 50
print(np.any(filedata > 50, axis=0))
print(np.any(filedata > 50, axis=1))

# If all of the values from any column/row is greater than 50
print(np.all(filedata > 50, axis=1))
print(np.all(filedata > 50, axis=0))


[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[ True  True  True]
[False False False]
[False False False False  True False False False False False False False
 False False False False False False]


In [51]:
print((filedata > 50) & (filedata < 100))

# Not
print(~((filedata > 50) & (filedata < 100)))

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
